services:
  login:
    image: login
    build:
      context: .
      dockerfile: ./apps/login/Dockerfile
      args:
        NEXT_PUBLIC_PORTAL_UI_BASE_URL: http://localhost:2001
        NEXT_PUBLIC_ADMIN_UI_BASE_URL: http://localhost:2002
        NEXT_PUBLIC_API_GATEWAY_BASE_URL: http://localhost:1000
    ports:
      - 2000:2000
    restart: on-failure

  portal:
    image: portal
    build:
      context: .
      dockerfile: ./apps/portal/Dockerfile
      args:
        NEXT_PUBLIC_LOGIN_UI_BASE_URL: http://localhost:2000
        NEXT_PUBLIC_API_GATEWAY_BASE_URL: http://localhost:1000
    ports:
      - 2001:2001
    restart: on-failure

  admin:
    image: admin
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
      args:
        NEXT_PUBLIC_LOGIN_UI_BASE_URL: http://localhost:2000
        NEXT_PUBLIC_API_GATEWAY_BASE_URL: http://localhost:1000
    ports:
      - 2002:2002
    restart: on-failure
