packages:
  - apps/*
  - packages/*

catalog:
  typescript: 5.8.3
  react: 19.1.0
  react-dom: 19.1.0
  next: 15.3.5
  react-hook-form: 7.61.1
  zod: 3.25.67
  tailwindcss: 4.1.11
  postcss: 8.5.6
  i18next: 25.3.4
  react-i18next: 15.6.1
  i18next-browser-languagedetector: 8.2.0
  react-cookie: 8.0.1
  jest: 30.0.5
  ts-jest: 29.4.1
  '@tailwindcss/postcss': 4.1.11
  '@hookform/resolvers': 3.9.0
  '@types/react': 19.1.8
  '@types/react-dom': 19.1.6
  '@types/node': 24.0.13
  '@tanstack/react-query': 5.76.2
  '@tanstack/react-table': 8.21.3
  '@tanstack/react-query-devtools': 5.76.2
  '@testing-library/jest-dom': 6.7.0
  '@types/jest': 30.0.0
  
