name: Lint Pull Request

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  lint-pull-request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - name: Lint pull request
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}